Algoritmo " 21 - Exercicios Sáida de Dados"
// Disciplina   :Udemy - Algoritmos e Lógica de Programação 2022
// Professor   : Udemy treinamento
// Descrição   : Testando saida de Dados
// Autor(a)    : Daniele Barbosa Gutinik
// Data atual  : 13/04/2022
Var
// Seção de Declarações das variáveis 



Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
    escreval("Bom dia !")
    escreva("Boa Noite.")

Fimalgoritmo