Algoritmo "23 - teste_Processamento_Dados"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Udemy
// Descrição   : calculando variaveil
// Autor(a)    : Daniele Barbosa Gutinik
// Data atual  : 13/04/2022
Var
// Seção de Declarações das variáveis 

  a, b, resultado : inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  a <- 5
  b <- 2
  
  resultado <- a \ b
  
  escreval(resultado)


Fimalgoritmo