Algoritmo "23 - Processamento de Dados"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Daniele Barbosa Gutinik
// Descrição   : testando processamento de dados
// Autor(a)    : Daniele Barbosa Gutinik
// Data atual  : 13/04/2022
Var
// Seção de Declarações das variáveis 

  x,y : inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

  x <- 5
  y <- 2 * 5
  
  escreval(x)
  escreval(y)


Fimalgoritmo