Algoritmo "Calculando _Area"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Udemy
// Descrição   : Calculando a Area
// Autor(a)    : Daniele Barbosa Gutinik
// Data atual  : 13/04/2022
Var
// Seção de Declarações das variáveis 
  b1, b2, h, area : real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  b1 <- 6.0
  b2 <- 8.0
  h <- 5.0
  
  area <- (b1 + b2)/ 2.0 * h;
  
  escreval(area)



Fimalgoritmo