Algoritmo "24- Entrada de Dados_Leia"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Udemy
// Descrição   : Ler para entrada de dados dentro do Programa
// Autor(a)    : Daniele Barbosa Gutinik
// Data atual  : 13/04/2022
Var
// Seção de Declarações das variáveis 
  x : inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  leia(x)
  
  escreval(x)


Fimalgoritmo